version: '3'
services:
  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_DATABASE: demo
      MYSQL_USER: demo
      MYSQL_PASSWORD: demo
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Tokyo
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
