spring:
    application:
        name: spring-boot-demo
    datasource:
        url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
        username: ${DB_USER}
        password: ${DB_PASS}
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: validate
        show-sql: true
    liquibase:
        change-log: classpath:/db/changelog/main-changelog.yaml
logging:
    level:
        root: ${LOG_LEVEL:INFO}
    pattern:
        console: "%date{yyyy-MM-dd HH:mm:ss.SSS} [%-5le] [%t] %C.%M:%L - %m%n"

---
spring:
    config:
        activate:
            on-profile: dev
        import: optional:file:.dev.env[.properties]
    liquibase:
        change-log: classpath:/db/changelog/dev-changelog.yaml

---
spring:
    config:
        activate:
            on-profile: test
        import: optional:file:.test.env[.properties]
    liquibase:
        change-log: classpath:/db/changelog/test-changelog.yaml
